<template>
  <body>
    <div class="content">
      <NavLinks/>
      <TitleComponent/>
      <!-- <iframe src="https://www.random.org/widgets/integers/iframe.php?title=True+Random+Number+Generator&amp;buttontxt=Generate&amp;width=160&amp;height=230&amp;border=on&amp;bgcolor=%23FFFFFF&amp;txtcolor=%23777777&amp;altbgcolor=%23CCCCFFA&amp;alttxtcolor=%23000000&amp;defaultmin=1&amp;defaultmax=100&amp;fixed=off" frameborder="0" width="160" height="235" style="min-height:235px;" scrolling="no" longdesc="https://www.random.org/integers/">
        The numbers generated by this widget come from RANDOM.ORG's true random number generator.
      </iframe> -->
      <MainRandom/>
      <ThingsBelow/>
      <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    </div>
  </body>
</template>

<script>
import NavLinks from './components/Sigleton Components/NavLinks.vue';
import TitleComponent from './components/Sigleton Components/TitleComponent.vue';

  export default{
    data(){
      return{

      }
    },
    components:{NavLinks, TitleComponent}
  }
</script>

<style>
  body{
    display: grid;
    justify-items: center;
    font-family: sans-serif;
  }

  .content{
    width: 800px;
    background-color: #c3c3c3; /* To remove later*/ 
  }
</style>